# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90e0cb22b829443c0d469f2e3662d1665011e2c70cec1f6599918056854067c37cae573157f7a8894ecf0470e464414296e99c689396f6382abaea5284c808f0
  cloudinary_cloud_name: <%= ENV['CLOUDINARY_CLOUD_NAME'] %>
  cloudinary_cloud_api_key: <%= ENV['CLOUDINARY_API_KEY'] %>
  cloudinary_cloud_api_secret: <%= ENV['CLOUDINARY_API_SECRET'] %>
test:
  secret_key_base: 57e5d5dbf2401dc36d1237a0bd2f08f102d1ea8a61169df176cba00a1c84eb960f4bdb8905a0fee8cfbb37476b8ddc67c131a798a3f107a835ebd7dc9b858c6d
  cloudinary_cloud_name: <%= ENV['CLOUDINARY_CLOUD_NAME'] %>
  cloudinary_cloud_api_key: <%= ENV['CLOUDINARY_API_KEY'] %>
  cloudinary_cloud_api_secret: <%= ENV['CLOUDINARY_API_SECRET'] %>
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  cloudinary_cloud_name: <%= ENV['CLOUDINARY_CLOUD_NAME'] %>
  cloudinary_cloud_api_key: <%= ENV['CLOUDINARY_API_KEY'] %>
  cloudinary_cloud_api_secret: <%= ENV['CLOUDINARY_API_SECRET'] %>
